# Generated by Django 5.1 on 2024-08-22 17:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("email_sent", models.BooleanField(default=False)),
                ("telegram_sent", models.BooleanField(default=False)),
            ],
        ),
    ]
