# Generated by Django 5.0.7 on 2024-08-07 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_email"),
        ("hackathons", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="emails",
            field=models.ManyToManyField(related_name="emails", to="accounts.email"),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
