# Generated by Django 5.0.7 on 2024-08-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0002_hackathon_emails_alter_hackathon_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="hackathon",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("ENDED", "Ended"),
                ],
                default="NOT_STARTED",
            ),
        ),
    ]
