# Generated by Django 5.1 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0004_role_userrole_role_users_alter_role_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hackathon",
            name="image_cover",
            field=models.BinaryField(),
        ),
    ]
