# Generated by Django 5.1 on 2024-08-20 20:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0004_role_userrole_role_users_alter_role_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackathon",
            name="id",
        ),
        migrations.AddField(
            model_name="hackathon",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="hackathon",
            name="status",
            field=models.CharField(
                choices=[
                    ("NOT_STARTED", "Not Started"),
                    ("STARTED", "Started"),
                    ("ENDED", "Ended"),
                ],
                default="NOT_STARTED",
                max_length=20,
            ),
        ),
    ]
