# Generated by Django 5.1 on 2024-08-20 22:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0005_remove_hackathon_id_hackathon_uuid_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hackathon",
            name="uuid",
        ),
        migrations.AddField(
            model_name="hackathon",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
