# Generated by Django 5.1 on 2024-08-20 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0005_alter_hackathon_image_cover"),
        ("hackathons", "0006_remove_hackathon_uuid_hackathon_id"),
    ]

    operations = []
