version: "3.9"
name: "megazord"

services:
  backend:
    container_name: "megazord-backend"

    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      db:
        condition: service_started
    networks:
      - megazord-network

    ports:
      - "8000:8000"

    environment:
      - DATABASE_USER=${DATABASE_USER:-megazord_user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-megazord_super_user}
      - DATABASE_DB=${DATABASE_DB:-megazord}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
    env_file:
      - .env

    volumes:
      - './src:/opt/src:ro'
      - './tests:/opt/tests:ro'

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_DB:-megazord}
      - POSTGRES_USER=${DATABASE_USER:-megazord_user}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-megazord_super_user}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - megazord-network

  frontend:
    container_name: "megazord-frontend"
    image: ghcr.io/open-cu/megazord-frontend:${FRONTEND_IMAGE_TAG:-main}
    ports:
      - "3000:3000"
    environment:
      - VITE_API_CLIENT=${API_URL:-http://localhost:8000/api}

volumes:
  db-data:

networks:
  megazord-network:
