name: "megazord-backend"

services:
  backend:
    restart: unless-stopped
    container_name: "megazord-backend"
    image: ghcr.io/open-cu/megazord-backend:${BACKEND_IMAGE_TAG:-main}

    depends_on:
      db:
        condition: service_started
    networks:
      - internal
      - proxy

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.megazord_backend.entrypoints=https"
      - "traefik.http.routers.megazord_backend.rule=Host(`$DEPLOY_DOMAIN`) && PathPrefix(`/api`)"
      - "traefik.http.services.megazord_backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.megazord_backend.tls.certresolver=letsEncrypt"
      - "traefik.docker.network=proxy"

    environment:
      - SERVER_PORT=8000
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:?error}
      - DEPLOY_DOMAIN=${DEPLOY_DOMAIN:?error}
      - CONFIRMATION_CODE_TTL=${CONFIRMATION_CODE_TTL:-2}

      - TELEGRAM_BOT_USERNAME=${TELEGRAM_BOT_USERNAME:?error}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:?error}

      - DATABASE_USER=${DATABASE_USER:?error}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:?error}
      - DATABASE_DB=${DATABASE_DB:?error}
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}

      - EMAIL_HOST=${EMAIL_HOST:?error}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_HOST_USER=${EMAIL_HOST_USER:?error}
      - EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD:?error}

  db:
    restart: unless-stopped
    container_name: "megazord-db"
    image: postgres:16

    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - internal

    environment:
      - POSTGRES_DB=${DATABASE_DB:?error}
      - POSTGRES_USER=${DATABASE_USER:?error}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:?error}

volumes:
  db-data:

networks:
  internal:
  proxy:
    external: true
