[tool.ruff]
src = ["src"]
line-length = 88
target-version = "py312"

[tool.ruff.lint]
select = [
    "F",      # Pyflakes
    "I",      # isort
#    "E",      # pycodestyle (Error)
#    "D",      # pydocstyle
    "YTT",    # flake8-2020
#    "B",      # flake8-bugbear
    "T10",    # flake8-debugger
    "T20",    # flake8-print
    "C4",     # flake8-comprehensions
    "PYI006", # flake8-pyi
]
pydocstyle = { convention = "google" }

[tool.ruff.format]
quote-style = "double"
docstring-code-format = true

[tool.coverage.run]
omit = ["tests/*", "/__main__.py", "/.venv/*", "**/site-packages/*"]
branch = true

[tool.coverage.report]
show_missing = true
#skip_covered = true
exclude_also = [
    "def repr",
    "raise NotImplementedError",
    "if name == .main.:",
    "if TYPE_CHECKING:",
    "class .*\\bProtocol\\):",
    "@(abc\\.)?abstractmethod",
    ]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "megazord.settings"

pythonpath = ["src"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = "--strict-markers --showlocals --verbosity 2"
log_level = "INFO"
