# Generated by Django 5.0.7 on 2024-08-10 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hackathons", "0002_hackathon_emails_alter_hackathon_participants"),
        ("resumes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="hhru",
            new_name="hh",
        ),
        migrations.AlterUniqueTogether(
            name="resume",
            unique_together={("user", "hackathon")},
        ),
        migrations.AlterField(
            model_name="hardskilltag",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hard_skills",
                to="resumes.resume",
            ),
        ),
        migrations.AlterField(
            model_name="softskilltag",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soft_skills",
                to="resumes.resume",
            ),
        ),
        migrations.RemoveField(
            model_name="resume",
            name="pdf",
        ),
    ]
