# Generated by Django 5.0.7 on 2024-08-08 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="telegram_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
