# Generated by Django 5.1 on 2024-08-20 20:55

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_account_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="id",
        ),
        migrations.AlterField(
            model_name="account",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
