# Generated by Django 5.1 on 2024-08-20 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_remove_account_id_alter_account_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="uuid",
            new_name="id",
        ),
    ]
