# Generated by Django 5.1 on 2024-08-20 22:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_confirmation_code"),
        ("accounts", "0006_rename_uuid_account_id"),
    ]

    operations = []
