name: Generate changelog

on:
  push:
    branches:
      - main
    tags:
      - "*"
env:
  CHANGELOG_FILE: "CHANGES.MD"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        env:
          OUTPUT: ${{ env.CHANGELOG_FILE }}
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.CHANGELOG_FILE }}
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
